# Generated by Django 6.0 on 2025-12-18 11:27

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveIndex(
            model_name='usermessage',
            name='accounts_us_user_id_3546ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='usermessage',
            name='accounts_us_is_from_0dbf78_idx',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='مستند شغلی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید ۱۰ رقم باشد', regex='^[0-9]{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', null=True, upload_to=accounts.models.user_profile_image_path, verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='contact_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='accounts.contactmessage', verbose_name='پیام تماس'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_type',
            field=models.CharField(choices=[('contact', 'پیام تماس'), ('response', 'پاسخ ادمین'), ('private', 'پیام خصوصی')], default='contact', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_user_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['user', 'is_read'], name='accounts_us_user_id_11bfa6_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['created_at'], name='accounts_us_created_431360_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['is_from_admin'], name='accounts_us_is_from_c18676_idx'),
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='receiver',
        ),
    ]
